### ISSUE TITLE
Need to bypass TFA

### ISSUE THREAD

**Issue by Monte1288** [cipheras/cipherginx#5]
Anyone help me to bypass TFA
![IMG_20220323_095200](https://user-images.githubusercontent.com/98557398/159623388-1d94e4de-689d-4ca9-8391-9288eeee98ec.jpg)

**Comment by cipheras** [comment]
This tool not exact;y bypass 2FA but uses MITM attack to steal it.

**Comment by Monte1288** [comment]
Can you please help me
My telegram is @piter648
